teleop_twist_joy_node:
  ros__parameters:
    axis_angular:
      pitch: -1
      roll: -1
      yaw: 0
    axis_linear:
      x: 1
      y: -1
      z: -1
    enable_button: 9
    enable_turbo_button: 7
    scale_angular:
      pitch: 0.393
      roll: 0.393
      yaw: 0.393
    scale_angular_turbo:
      pitch: 0.786
      roll: 0.786
      yaw: 0.786
    scale_linear:
      x: 0.20
      y: 0.20
      z: 0.20
    scale_linear_turbo:
      x: 0.40
      y: 0.40
      z: 0.40
    use_sim_time: false
